### ISSUE TITLE
Transfer the repository to the project or institute repository

### ISSUE THREAD

**Issue by monodera** [Subaru-PFS/spt_target_uploader#228]
I saw that this repository is quoted in the He-san's draft and I think that it would be an good opportunity to transfer this repository to either @Subaru-PFS (PFS project repository) or @Subaru-SciOp (Subaru's science operation repository). Which is more appropriate? @yukimoritani @takagi-naoj 

I'm wondering if the transfer remove all issues as it seems that the `Issues` is disabled in the PFS repository. In this case, I should make them as Jira tickets before doing so.

**Comment by takagi-naoj** [comment]
I have talked with @yukimoritani about this, and we suggest:
- Use Subaru-PFS to manage stuff developed by PFS project and obsproc (especially during the commissioning)
- Use Sudaru-Sciop to manage stuff developed by Subaru science operation (like website or other tools that might be made by the SA in the future)

So I think it will be good to transfer it to Subaru-PFS.

**Comment by monodera** [comment]
sounds reasonable to me. Then, I have a few questions:

- Can the repository name be kept as `pfs_target_uploader` or need to be changed to conform the naming convention of the project (e.g., `spt_target_uploader`)?
- Do you know if Issues will be kept? I think `Subaru-PFS` disables Issues by default.

**Comment by yukimoritani** [comment]
(I'm so sorry to be super late to this...) According to  our repository name convention,

> pfs_ Repositories for project general
> spt_ Survey Planning and Targetting (SPT) sofotware, includes survey coordination and operation, exposure time calculator, and so on.

So, spt_ sounds matched to me, as uploader cares observation plan.

Yes, to encourage discussion on JIRA, the repositories doesn't have Issue by default.. when I create a new one, I manually disable it. But because you already have had many discussions.. maybe we should think an exception.

**Comment by monodera** [comment]
Transfer is done. New repository is `Subaru-PFS/spt_target_uploader`. You can modify the origin of your local one by `git remote set-url origin https://github.com/Subaru-PFS/spt_target_uploader.git`.
